version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: testdb-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: testdb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: