services:
  mongodb:
    image: mongo:7.0
    container_name: testdb-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: testdb
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__ConnectionString=mongodb://mongodb:27017
      - MongoDb__MongoDbDatabaseName=testdb
    depends_on:
      - mongodb

volumes:
  mongo_data: